#this is the deployment file
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: ingress-nginx
  labels:
    app: weather-forecast
spec:
  replicas: 2
  selector:
    matchLabels:
      service: webapp
  template:
    metadata:
      labels:
        app: weather-forecast
        service: webapp
    spec:
      containers:
        - name: webapp
          image: acrmediawestus3.azurecr.io/princecicdpocaspnetrepo:$(tag)
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
