#this is the deployment file
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: dev-astrology-controller
  labels:
    app: weather-forecast
spec:
  replicas: 2
  selector:
    matchLabels:
      service: webapp
  template:
    metadata:
      labels:
        app: weather-forecast
        service: webapp
    spec:
      containers:
      - name: webapp
        image: acrmediawestus3.azurecr.io/princecicdpocaspnetrepo:($tag)
        ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
      nodeSelector:
        agentpool: stagingpool
