#this is service yml
apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: weather-forecast
    service: webapp
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.50.0.117
  ports:
    - port: 443
      targetPort: 80
      protocol: TCP
  selector:
    service: webapp
