#this is service yml
apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: ingress-controller
  labels:
    app: weather-forecast
    service: webapp
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    service: webapp
    
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-ingress
  namespace: ingress-controller
  # annotations:
    # nginx.ingress.kubernetes.io/ssl-redirect: "false"

spec:
  # tls:
  #     - hosts:
  #       - dev.horoscopo.com
  #       secretName: dev-horoscopo-secret2
  ingressClassName: nginx
  rules:
  # - host: dev.horoscopo.com
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webapp
            port:
              number: 80
